### PR TITLE
Fix the bug when loading model from local path.

### PR DESCRIPTION
**Pull request by APengX**
#21 
Fix the bug when loading model from local path.

from snac import SNAC
snacmodel = SNAC.from_pretrained(Path("/root/XXX/model/snac_24khz")).eval().to(device)

### CODE REVIEW

**Comment by hubertsiuzdak** [comment]
Instead of wrapping the string path with a `pathlib.Path` object, we can just use `os.path.isdir()` to check the filesystem path. 

This is also how huggingface handles it in [hub_mixin.py](https://github.com/huggingface/huggingface_hub/blob/855755b3a97105f9d6479123cbb4f560a27eacf8/src/huggingface_hub/hub_mixin.py#L504-L513)

Would you mind updating the PR with this change?

**Comment by Pongking** [comment]
Thank you very much, I will modify it immediately :)

**Comment by Pongking** [comment]
Thank you so much,that's really a great learning opportunity for me.thank you!!

**Comment by sankexin** [comment]
snacmodel = SNAC.from_pretrained("hubertsiuzdak/snac_24khz", local_dir="/root/mini-omni/snac_24khz",).eval().to(device)

**Pull request merged**
